const leaseData: Lease[] = [
  {
    identifier: "HSBC 2",
    type: "Motor Vehicle",
    contractNumber: "301861",
    registrationDoc: "YE71CLO",
    makeModel: "RENAULT TRAFIC LWB 30 2.0DCI",
    startDate: "",
    termMonths: "",
    endDate: "",
    netCapital: "£27,278.00",
    capitalCost: "",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "£0.00",
    vehicles: [
      {
        registration: "YE71CLO",
        model: "RENAULT TRAFIC LWB 30 2.0DCI",
        netCapital: "£27,278.00",
      },
    ],
  },
  {
    identifier: "HSBC 22",
    type: "Motor Vehicle",
    contractNumber: "297162",
    registrationDoc: "YC21 OCL",
    makeModel: "Renault Energy 120 DCI Van",
    startDate: "10 May 2021",
    termMonths: "48",
    endDate: "28 September 2024",
    netCapital: "£22,375.00",
    capitalCost: "£108,720.00",
    arrangementFee: "£50.00",
    financeInterest: "£4,429.48",
    initialPayment: "£22,441.00",
    monthlyInstallment: "£1,889.76",
    finalPayment: "£0.00",
    totalRepayment: "£113,149.48",
    vehicles: [
      {
        registration: "YC21 OCL",
        model: "Renault Energy 120 DCI Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC21 OCG",
        model: "Renault Energy Dci 120 Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "YE21 AGZ",
        model: "Renaukt Energy Dei 120 Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC21 OHO",
        model: "Renault Energy Dei 120 Van",
        netCapital: "£22,375.00",
      },
    ],
  },
  {
    identifier: "HSBC 6",
    type: "Motor Vehicle",
    contractNumber: "302839",
    registrationDoc: "YP71WRN",
    makeModel: "Renault Trafic Sl28 DCi 170",
    startDate: "10 December 2021",
    termMonths: "48",
    endDate: "28 September 2024",
    netCapital: "£27,278.00",
    capitalCost: "£100,336.80",
    arrangementFee: "£50.00",
    financeInterest: "£5,396.83",
    initialPayment: "£20,746.75",
    monthlyInstallment: "£1,770.56",
    finalPayment: "£0.00",
    totalRepayment: "£105,733.63",
    vehicles: [
      {
        registration: "YP71WRN",
        model: "Renault Trafic Sl28 DCi 170",
        netCapital: "£27,278.00",
      },
      {
        registration: "YP71WRG",
        model: "Renault Trafic SI28 DCi 170",
        netCapital: "£27,278.00",
      },
      {
        registration: "YVP71RZM",
        model: "Renault Trafic LL20 DCi 170",
        netCapital: "£28,233.00",
      },
    ],
  },
  {
    identifier: "HSBC 10",
    type: "Equipment",
    contractNumber: "300961",
    registrationDoc: "-",
    makeModel: "Hydro Power 3000psi Jet Vac System With MK2-11 Wincam Plus Pro",
    startDate: "01 October 2021",
    termMonths: "30",
    endDate: "28 September 2024",
    netCapital: "£18,712.68",
    capitalCost: "£22,455.22",
    arrangementFee: "£50.00",
    financeInterest: "£648.36",
    initialPayment: "£4,678.17",
    monthlyInstallment: "£614.18",
    finalPayment: "£0.00",
    totalRepayment: "£23,103.57",
    vehicles: [
      {
        registration: "Equipment",
        model: "Hydro Power 3000psi Jet Vac System With MK2-11 Wincam Plus Pro",
        netCapital: "£18,712.68",
      },
    ],
  },
  {
    identifier: "HSBC 7",
    type: "Motor Vehicle",
    contractNumber: "301861",
    registrationDoc: "YE71DZX",
    makeModel: "RENAULT TRAFIC LWB 30 2.0CI",
    startDate: "18 December 2021",
    termMonths: "48",
    endDate: "18 December 2025",
    netCapital: "£27,278.00",
    capitalCost: "£196,353.58",
    arrangementFee: "£50.00",
    financeInterest: "£10,296.86",
    initialPayment: "£40,593.50",
    monthlyInstallment: "£3,459.52",
    finalPayment: "£0.00",
    totalRepayment: "£206,650.46",
    vehicles: [
      {
        registration: "YE71DZX",
        model: "RENAULT TRAFIC LWB 30 2.0CI",
        netCapital: "£27,278.00",
      },
    ],
  },
  {
    identifier: "HSBC 1",
    type: "Motor Vehicle",
    contractNumber: "309651",
    registrationDoc: "BT70XMO",
    makeModel: "Peugeot Boxer PROFESSIONAL L3H2 2.2 BLUE",
    startDate: "26 August 2022",
    termMonths: "48",
    endDate: "26 August 2026",
    netCapital: "£28,015.00",
    capitalCost: "£33,948.00",
    arrangementFee: "£50.00",
    financeInterest: "£2,973.78",
    initialPayment: "£8,404.50",
    monthlyInstallment: "£594.11",
    finalPayment: "-",
    totalRepayment: "36,921.78",
    vehicles: [
      {
        registration: "BT70XMO",
        model: "Peugeot Boxer PROFESSIONAL L3H2 2.2 BLUE",
        netCapital: "£28,015.00",
      },
    ],
  },
  {
    identifier: "HSBC 5",
    type: "Motor Vehicle",
    contractNumber: "302840",
    registrationDoc: "YVP71 JUK",
    makeModel: "Renault Trafic SL28 DCi 145",
    startDate: "13 December 2021",
    termMonths: "48",
    endDate: "13 December 2025",
    netCapital: "£25,588.00",
    capitalCost: "£97,162.80",
    arrangementFee: "£50.00",
    financeInterest: "£5,226.38",
    initialPayment: "£20,085.50",
    monthlyInstallment: "£1,714.66",
    finalPayment: "",
    totalRepayment: "102,389.18",
    vehicles: [
      {
        registration: "YVP71 JUK",
        model: "Renault Trafic SL28 DCi 145",
        netCapital: "£25,588.00",
      },
      {
        registration: "YP71 OHA",
        model: "Renault Trafic LL30 DCi 170",
        netCapital: "£27,278.00",
      },
      {
        registration: "YP71 SMX",
        model: "Renault Trafic LL30 DCi 170",
        netCapital: "£27,278.00",
      },
    ],
  },
  {
    identifier: "HSBC 8 -1",
    type: "Motor Vehicle",
    contractNumber: "301798",
    registrationDoc: "DU19 YTB",
    makeModel: "Vauxhall Astra Estate SRI Nav 1.4 Petrol 2019",
    startDate: "16 November 2021",
    termMonths: "48",
    endDate: "16 November 2025",
    netCapital: "£20,500.00",
    capitalCost: "£20,500.00",
    arrangementFee: "£50.00",
    financeInterest: "£1,134.68",
    initialPayment: "£3,075.00",
    monthlyInstallment: "£386.66",
    finalPayment: "-",
    totalRepayment: "21,634.68",
    vehicles: [
      {
        registration: "DU19 YTB",
        model: "Vauxhall Astra Estate SRI Nav 1.4 Petrol 2019",
        netCapital: "£20,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 9",
    type: "Motor Vehicle",
    contractNumber: "300999",
    registrationDoc: "YR71UHA",
    makeModel: "Renault Trafic LWB",
    startDate: "18 October 2021",
    termMonths: "48",
    endDate: "18 October 2025",
    netCapital: "£25,528.00",
    capitalCost: "£164,076.00",
    arrangementFee: "£50.00",
    financeInterest: "£7,209.25",
    initialPayment: "£33,921.25",
    monthlyInstallment: "£2,861.75",
    finalPayment: "",
    totalRepayment: "171,285.25",
    vehicles: [
      {
        registration: "YR71UHA",
        model: "Renault Trafic LWB",
        netCapital: "£25,528.00",
      },
      {
        registration: "YH71XYJ",
        model: "Renault Trafic LWB",
        netCapital: "£27,218.00",
      },
      {
        registration: "YT71ZYF",
        model: "Renault Trafic LWB",
        netCapital: "£27,218.00",
      },
      {
        registration: "YH71WNC",
        model: "Renault Trafic LWB",
        netCapital: "£27,218.00",
      },
      {
        registration: "YH71WND",
        model: "Renault Trafic LWB",
        netCapital: "£28,173.00",
      },
    ],
  },
  {
    identifier: "HSBC 16",
    type: "Motor Vehicle",
    contractNumber: "299817",
    registrationDoc: "YE21COF",
    makeModel: "Renault Trafic Crew LL30 Energy",
    startDate: "Sep 15, 2021",
    termMonths: "48",
    endDate: "Sep 15, 2025",
    netCapital: "£25,310.00",
    capitalCost: "£60,057.60",
    arrangementFee: "£50.00",
    financeInterest: "£2,504.14",
    initialPayment: "£12,407.50",
    monthlyInstallment: "£1,044.88",
    finalPayment: "",
    totalRepayment: "62,561.74",
    vehicles: [
      {
        registration: "YE21COF",
        model: "Renault Trafic Crew LL30 Energy",
        netCapital: "£25,310.00",
      },
      {
        registration: "YO21BYK",
        model: "Renault Trafic Crew LL30 Energy",
        netCapital: "£24,188.00",
      },
    ],
  },
  {
    identifier: "HSBC 18",
    type: "Motor Vehicle",
    contractNumber: "299061",
    registrationDoc: "YC21JU.J",
    makeModel: "Renault Trafic SL28 Energy",
    startDate: "20 July 2021",
    termMonths: "48",
    endDate: "20 July 2025",
    netCapital: "£22,560.00",
    capitalCost: "£109,608.00",
    arrangementFee: "£50.00",
    financeInterest: "£4,592.40",
    initialPayment: "£22,626.00",
    monthlyInstallment: "£1,907.80",
    finalPayment: "",
    totalRepayment: "114,200.40",
    vehicles: [
      {
        registration: "YC21JU.J",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£22,560.00",
      },
      {
        registration: "YH21ZPU",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£22,560.00",
      },
      {
        registration: "YH21ZPL",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£22,560.00",
      },
      {
        registration: "YH21ZPW",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£22,560.00",
      },
      {
        registration: "YC21 NZP",
        model: "Renault Traffic SL28 Energy",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC21 NZR",
        model: "Renault Traffic SL28 Energy",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC21 NZM",
        model: "Renault Traffic SL28 Energy",
        netCapital: "£22,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 20",
    type: "Motor Vehicle",
    contractNumber: "298039",
    registrationDoc: "YC21 NZO",
    makeModel: "Renault Traffic SL28 Energy",
    startDate: "",
    termMonths: "",
    endDate: "",
    netCapital: "£22,500.00",
    capitalCost: "",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "-",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC21 NZO",
        model: "Renault Traffic SL28 Energy",
        netCapital: "£22,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 3",
    type: "Motor Vehicle",
    contractNumber: "303740",
    registrationDoc: "KS70 ORP",
    makeModel: "Audi Q7 S Line 55 TFSi e Quattro",
    startDate: "03 March 2022",
    termMonths: "48",
    endDate: "03 March 2026",
    netCapital: "£57,500.00",
    capitalCost: "£69,480.00",
    arrangementFee: "£50.00",
    financeInterest: "£5,232.00",
    initialPayment: "£6,998.00",
    monthlyInstallment: "£1,411.75",
    finalPayment: "-",
    totalRepayment: "74,762.00",
    vehicles: [
      {
        registration: "KS70 ORP",
        model: "Audi Q7 S Line 55 TFSi e Quattro",
        netCapital: "£57,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 4",
    type: "Motor Vehicle",
    contractNumber: "302841",
    registrationDoc: "YF71EKO",
    makeModel: "Renault TraficLL30 DCi 170 BLACK EDITION",
    startDate: "13 January 2022",
    termMonths: "",
    endDate: "13 January 2026",
    netCapital: "£27,278.00",
    capitalCost: "£199,191.60",
    arrangementFee: "£50.00",
    financeInterest: "£10,713.63",
    initialPayment: "£41,184.75",
    monthlyInstallment: "£3,515.01",
    finalPayment: "",
    totalRepayment: "209,905.23",
    vehicles: [
      {
        registration: "YF71EKO",
        model: "Renault TraficLL30 DCi 170 BLACK EDITION",
        netCapital: "£27,278.00",
      },
      {
        registration: "YP7 1MVA",
        model: "Renault Trafic SL28 Energy Sport Nav",
        netCapital: "£28,233.00",
      },
      {
        registration: "YE71FZL",
        model: "Renault Trafic LL30 Energy Black Edition",
        netCapital: "£27,278.00",
      },
      {
        registration: "YP71MUO",
        model: "Renault Trafic LL30 Energy Sport Nav",
        netCapital: "£27,733.00",
      },
      {
        registration: "YE710YW",
        model: "Renault Trafic LWB Black Edition",
        netCapital: "£28,233.00",
      },
      {
        registration: "YP71SNJ",
        model: "Renault Trafic SL28 Energy Sport Nav",
        netCapital: "£25,588.00",
      },
    ],
  },
  {
    identifier: "HSBC 12",
    type: "Motor Vehicle",
    contractNumber: "301994",
    registrationDoc: "LB19YYR",
    makeModel: "Vauxhall Astra Elite Auto Nav Turbo",
    startDate: "16 November 2021",
    termMonths: "48",
    endDate: "16 November 2025",
    netCapital: "£20,250.00",
    capitalCost: "£20,250.00",
    arrangementFee: "£50.00",
    financeInterest: "£1,137.90",
    initialPayment: "£3,037.50",
    monthlyInstallment: "£382.30",
    finalPayment: "-",
    totalRepayment: "21,387.90",
    vehicles: [
      {
        registration: "LB19YYR",
        model: "Vauxhall Astra Elite Auto Nav Turbo",
        netCapital: "£20,250.00",
      },
    ],
  },
  {
    identifier: "HSBC 13",
    type: "Motor Vehicle",
    contractNumber: "301958",
    registrationDoc: "YG71UXE",
    makeModel: "Renault Trafic SL28 Energy",
    startDate: "15 November 2021",
    termMonths: "",
    endDate: "15 November 2025",
    netCapital: "£25,588.00",
    capitalCost: "£62,071.20",
    arrangementFee: "£50.00",
    financeInterest: "£3,255.32",
    initialPayment: "£12,827.00",
    monthlyInstallment: "£1,093.74",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YG71UXE",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£25,588.00",
      },
      {
        registration: "YK71ZTX",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£25,588.00",
      },
    ],
  },
  {
    identifier: "HSBC 14",
    type: "Motor Vehicle",
    contractNumber: "301330",
    registrationDoc: "YC71GMY",
    makeModel: "Renault Trafic 30 LWB",
    startDate: "27 October 2021",
    termMonths: "",
    endDate: "27 October 2025",
    netCapital: "£27,218.00",
    capitalCost: "£162,528.00",
    arrangementFee: "£50.00",
    financeInterest: "£8,211.07",
    initialPayment: "£33,598.75",
    monthlyInstallment: "£2,857.09",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC71GMY",
        model: "Renault Trafic 30 LWB",
        netCapital: "£27,218.00",
      },
      {
        registration: "YC71VRR",
        model: "Renaullt Trafic LL30 Energy 145 Sport Nav",
        netCapital: "£25,928.00",
      },
      {
        registration: "YC71HWR",
        model: "Renault Trafic SL28 Energy",
        netCapital: "£27,218.00",
      },
      {
        registration: "YC71USG",
        model: "Renault Trafic LWB Sport Nav",
        netCapital: "£28,173.00",
      },
      {
        registration: "YC71SNF",
        model: "Renault Trafic LWB Sport Nav",
        netCapital: "£25,528.00",
      },
    ],
  },
  {
    identifier: "HSBC 19",
    type: "Motor Vehicle",
    contractNumber: "298466",
    registrationDoc: "YC21MKD",
    makeModel: "Renault Traffic Van",
    startDate: "02 July 2021",
    termMonths: "",
    endDate: "02 July 2025",
    netCapital: "£22,500.00",
    capitalCost: "£109,320.00",
    arrangementFee: "£50.00",
    financeInterest: "£4,524.72",
    initialPayment: "£22,566.00",
    monthlyInstallment: "£1,901.64",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC21MKD",
        model: "Renault Traffic Van",
        netCapital: "£22,500.00",
      },
      {
        registration: "YC21MKE",
        model: "Renault Traffic Van",
        netCapital: "£22,500.00",
      },
      {
        registration: "YC21 MKK",
        model: "Renault Traffic Van",
        netCapital: "£22,500.00",
      },
      {
        registration: "YC21NZN",
        model: "Renault Traffic Van",
        netCapital: "£22,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 23",
    type: "Motor Vehicle",
    contractNumber: "295547",
    registrationDoc: "YB21WPN",
    makeModel: "Renault Trafic SI28 DCi 145 Bus",
    startDate: "07 April 2021",
    termMonths: "48",
    endDate: "07 April 2025",
    netCapital: "£23,125.00",
    capitalCost: "£28,070.00",
    arrangementFee: "£50.00",
    financeInterest: "£1,135.73",
    initialPayment: "£5,781.25",
    monthlyInstallment: "£488.01",
    finalPayment: "-",
    totalRepayment: "29,205.73",
    vehicles: [
      {
        registration: "YB21WPN",
        model: "Renault Trafic SI28 DCi 145 Bus",
        netCapital: "£23,125.00",
      },
    ],
  },
  {
    identifier: "HSBC 11",
    type: "Equipment",
    contractNumber: "301740",
    registrationDoc: "",
    makeModel: "Roof Leak Detection Kits",
    startDate: "16 November 2021",
    termMonths: "36",
    endDate: "16 November 2024",
    netCapital: "£3,249.90",
    capitalCost: "£58,498.20",
    arrangementFee: "£50.00",
    financeInterest: "£2,408.46",
    initialPayment: "£12,187.13",
    monthlyInstallment: "£1,353.32",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
      {
        registration: "Equipment",
        model: "Roof Leak Detection Kits",
        netCapital: "£3,249.90",
      },
    ],
  },
  {
    identifier: "HSBC 17",
    type: "Equipment",
    contractNumber: "299558",
    registrationDoc: "",
    makeModel: "Air Moving & Drying Equipment",
    startDate: "15 October 2021",
    termMonths: "36",
    endDate: "15 October 2024",
    netCapital: "£33,918.84",
    capitalCost: "£40,702.61",
    arrangementFee: "£50.00",
    financeInterest: "£1,347.82",
    initialPayment: "£8,479.70",
    monthlyInstallment: "£932.52",
    finalPayment: "-",
    totalRepayment: "42,050.42",
    vehicles: [
      {
        registration: "Equipment",
        model: "Air Moving & Drying Equipment",
        netCapital: "£33,918.84",
      },
    ],
  },
  {
    identifier: "HSBC 27",
    type: "Motor Vehicle",
    contractNumber: "283425",
    registrationDoc: "EO69FZT",
    makeModel: "Audi e Tron",
    startDate: "Sep 25, 2019",
    termMonths: "48",
    endDate: "Sep 25, 2023",
    netCapital: "£62,037.50",
    capitalCost: "£74,500.00",
    arrangementFee: "£50.00",
    financeInterest: "£5,815.20",
    initialPayment: "£7,450.00",
    monthlyInstallment: "£1,052.40",
    finalPayment: "22,350.00",
    totalRepayment: "80,315.20",
    vehicles: [
      {
        registration: "EO69FZT",
        model: "Audi e Tron",
        netCapital: "£62,037.50",
      },
    ],
  },
  {
    identifier: "HSBC 25",
    type: "Equipment",
    contractNumber: "291576",
    registrationDoc: "",
    makeModel: "Leak Detection Equipment",
    startDate: "16 October 2020",
    termMonths: "36",
    endDate: "16 October 2023",
    netCapital: "£81,085.70",
    capitalCost: "£97,302.84",
    arrangementFee: "£50.00",
    financeInterest: "£3,036.87",
    initialPayment: "£24,325.71",
    monthlyInstallment: "£2,111.50",
    finalPayment: "-",
    totalRepayment: "100,339.71",
    vehicles: [
      {
        registration: "Equipment",
        model: "Leak Detection Equipment",
        netCapital: "£81,085.70",
      },
    ],
  },
  {
    identifier: "HSBC 24",
    type: "Equipment",
    contractNumber: "293477",
    registrationDoc: "",
    makeModel: "Leak Detection Equipment",
    startDate: "04 March 2021",
    termMonths: "36",
    endDate: "04 March 2024",
    netCapital: "£190,316.65",
    capitalCost: "£228,379.98",
    arrangementFee: "£150.00",
    financeInterest: "£7,020.50",
    initialPayment: "£57,095.00",
    monthlyInstallment: "£4,952.93",
    finalPayment: "-",
    totalRepayment: "235,400.48",
    vehicles: [
      {
        registration: "Equipment",
        model: "Leak Detection Equipment",
        netCapital: "£190,316.65",
      },
    ],
  },
  {
    identifier: "HSBC 26",
    type: "Motor Vehicle",
    contractNumber: "286738",
    registrationDoc: "BN20W",
    makeModel: "Nissan Navara Tekna DC190 Manual",
    startDate: "16 March 2020",
    termMonths: "48",
    endDate: "16 March 2024",
    netCapital: "£29,090.00",
    capitalCost: "£35,223.00",
    arrangementFee: "£50.00",
    financeInterest: "£1,648.80",
    initialPayment: "£8,727.00",
    monthlyInstallment: "£586.35",
    finalPayment: "-",
    totalRepayment: "36,871.80",
    vehicles: [
      {
        registration: "BN20W",
        model: "Nissan Navara Tekna DC190 Manual",
        netCapital: "£29,090.00",
      },
    ],
  },
  {
    identifier: "HSBC 28",
    type: "Motor Vehicle",
    contractNumber: "282958",
    registrationDoc: "YC19EPT",
    makeModel: "Renault Traffic Van",
    startDate: "25 September 2019",
    termMonths: "48",
    endDate: "25 September 2023",
    netCapital: "£18,780.00",
    capitalCost: "£114,255.00",
    arrangementFee: "£50.00",
    financeInterest: "£5,832.99",
    initialPayment: "£23,553.75",
    monthlyInstallment: "£2,011.13",
    finalPayment: "",
    totalRepayment: "120,087.99",
    vehicles: [
      {
        registration: "YC19EPT",
        model: "Renault Traffic Van",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ERD",
        model: "Renault Traffic Van",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ERF",
        model: "Renault Traffic Van",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19 ERR",
        model: "Renault Traffic Van",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19EPR",
        model: "Renault Traffic Van",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19EMY",
        model: "Renault Traffic SL27 Dei 120",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19EPB",
        model: "Renault Traffic SL27 Dei 120",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ESP",
        model: "Renault Traffic SL27 Dei 120",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ESR",
        model: "Renault Traffic SL27 Dei 120",
        netCapital: "£18,780.00",
      },
    ],
  },
  {
    identifier: "HSBC 29",
    type: "Motor Vehicle",
    contractNumber: "282959",
    registrationDoc: "YC19ESS",
    makeModel: "Renault Traffic SL27 Dei 120",
    startDate: "",
    termMonths: "",
    endDate: "",
    netCapital: "£18,780.00",
    capitalCost: "",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "-",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC19ESS",
        model: "Renault Traffic SL27 Dei 120",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ENB",
        model: "Renault Traffic Sl27 120Dci",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19EPH",
        model: "Renault Traffic Sl27 120Dci",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19ESK",
        model: "Renault Traffic Sl27 120Dci",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC19EST",
        model: "Renault Traffic Sl27 120Dci",
        netCapital: "£18,780.00",
      },
    ],
  },
  {
    identifier: "HSBC 30",
    type: "Motor Vehicle",
    contractNumber: "282241",
    registrationDoc: "YC19ESZ",
    makeModel: "Renault Traffic Sl27 120Dci",
    startDate: "",
    termMonths: "",
    endDate: "",
    netCapital: "£18,780.00",
    capitalCost: "",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "-",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC19ESZ",
        model: "Renault Traffic Sl27 120Dci",
        netCapital: "£18,780.00",
      },
      {
        registration: "YC21NZK",
        model: "Renault Energy 120 Dei Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC210CH",
        model: "Renault Energy 120 Dei Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "YC210CJ",
        model: "Renault Energy 120 Dei Van",
        netCapital: "£22,375.00",
      },
    ],
  },
  {
    identifier: "HSBC 21",
    type: "Motor Vehicle",
    contractNumber: "297339",
    registrationDoc: "YC210CF",
    makeModel: "Renault Energy 120 Dei Van",
    startDate: "",
    termMonths: "",
    endDate: "",
    netCapital: "£22,375.00",
    capitalCost: "",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "-",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC210CF",
        model: "Renault Energy 120 Dei Van",
        netCapital: "£22,375.00",
      },
      {
        registration: "Equipment",
        model: "Hydro Power Jetting Unit",
        netCapital: "£17,871.24",
      },
      {
        registration: "Equipment",
        model: "Hydro Power Jetting Unit",
        netCapital: "£17,871.24",
      },
      {
        registration: "LJ22 EXF",
        model: "Rioned Riocom 7.5t Jetvac",
        netCapital: "£117,995.00",
      },
      {
        registration: "BK21EVV",
        model: "Peugeot Expert L2H1 Van 332",
        netCapital: "£26,766.41",
      },
      {
        registration: "BK21KDO",
        model: "Peugeot Expert L2H1 Van 334",
        netCapital: "£26,566.41",
      },
      {
        registration: "BK21EUV",
        model: "Peugeot Expert L2H1 Van 333",
        netCapital: "£26,366.41",
      },
      {
        registration: "BK21EBF",
        model: "Peugeot Expert L2H1 Van 335",
        netCapital: "£26,566.41",
      },
      {
        registration: "BK21DZO",
        model: "Peugeot Expert L2H1 Van 337",
        netCapital: "£26,766.41",
      },
      {
        registration: "BK21XFR",
        model: "Peugeot Expert L2H1 Van 336",
        netCapital: "£26,441.41",
      },
      {
        registration: "LB22 AYU",
        model: "Renault Traffic LL30 Sport Blue DC Van with Hydro Power Supplies",
        netCapital: "£51,256.28",
      },
      {
        registration: "LF72 EPD",
        model: "Renault Traffic LL30 Sport Blue DC Van with Hydro Power Supplies",
        netCapital: "£51,256.28",
      },
      {
        registration: "LA22 JBX",
        model: "Renault Traffic LL30 Sport Blue DC Van with Hydro Power Supplies",
        netCapital: "£51,256.28",
      },
      {
        registration: "LB71 XGS",
        model: "Renault Traffic LL30 Sport Blue DC Van with Hydro Power Supplies",
        netCapital: "£51,256.28",
      },
      {
        registration: "YF72 PNZ",
        model: "Renault traffic SL28 DCI 130 Bus",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72 PSX",
        model: "Renault traffic SL28 DCI 130 Bus",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72 PSZ",
        model: "Renault traffic SL28 DCI 130 Bus",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72 TTE",
        model: "Renault traffic SL28 DCI 130 Bus",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72UAU",
        model: "TRAFIC SL28 DCI 130 BUS",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72UFG",
        model: "TRAFIC SL28 DCI 130 BUS",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72SBU",
        model: "TRAFIC SL28 DCI 130 BUS",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72TTV",
        model: "TRAFIC SL28 DCI 130 BUS",
        netCapital: "£26,486.00",
      },
      {
        registration: "YF72OVO",
        model: "RENAULT TRAFICLL3O DCI SPORT",
        netCapital: "£31,140.00",
      },
      {
        registration: "YE72KNF",
        model: "RENAULT TRAFIC LL3O DCI SPORT",
        netCapital: "£31,140.00",
      },
      {
        registration: "YF72OVS",
        model: "RENAULT TRAFIC LL3O DCI SPORT",
        netCapital: "£31,140.00",
      },
      {
        registration: "YF72OWV",
        model: "RENAULT TRAFIC LL3O DCI SPORT",
        netCapital: "£31,140.00",
      },
      {
        registration: "YE72AHJ",
        model: "RENAULT TRAFIC LL3O DCI SPORT",
        netCapital: "£31,140.00",
      },
      {
        registration: "LJ72 BZM",
        model: "Mitsubishi Canter 7.5t Vacuum Tanker",
        netCapital: "£132,160.00",
      },
      {
        registration: "YE72AHK",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£31,140.00",
      },
      {
        registration: "YE72AHL",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£31,140.00",
      },
      {
        registration: "YE72AHN",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£31,140.00",
      },
      {
        registration: "YE72AHP",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£31,140.00",
      },
      {
        registration: "YF72OWJ",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£31,140.00",
      },
      {
        registration: "CK24PHY",
        model: "AUDI A3",
        netCapital: "£27,412.50",
      },
      {
        registration: "DY24HZE",
        model: "NISSAN INTERSTAR F35",
        netCapital: "£44,220.00",
      },
      {
        registration: "DY24HZD",
        model: "NISSAN INTERSTAR F35",
        netCapital: "£44,220.00",
      },
      {
        registration: "DY24HZC",
        model: "NISSAN INTERSTAR F35",
        netCapital: "£44,220.00",
      },
      {
        registration: "DY24HZA",
        model: "NISSAN INTERSTAR F35",
        netCapital: "£44,220.00",
      },
      {
        registration: "YB73RHX",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£30,870.00",
      },
      {
        registration: "HN73PFO",
        model: "HYUNDAI KONA HATCH CAR",
        netCapital: "£29,450.00",
      },
      {
        registration: "YB73PYO",
        model: "RENAULT TRAFIC LL30 DCI SPORT VAN",
        netCapital: "£30,870.00",
      },
      {
        registration: "YF73ETO",
        model: "NISSAN PRIMASTARS 30 L1H1 110 ACENTA",
        netCapital: "£31,166.00",
      },
      {
        registration: "YF23ETR",
        model: "NISSAN PRIMASTARS 30 L1H1 110 ACENTA",
        netCapital: "£31,166.00",
      },
      {
        registration: "YF73OYG",
        model: "NISSAN PRIMASTARS 30 L1H1 110 ACENTA",
        netCapital: "£31,166.00",
      },
      {
        registration: "YF73RVM",
        model: "NISSAN PRIMASTARS 30 L1H1 110 ACENTA",
        netCapital: "£31,166.00",
      },
      {
        registration: "YF73ZVS",
        model: "NISSAN PRIMASTARS 30 L1H1 110 ACENTA",
        netCapital: "£31,166.00",
      },
      {
        registration: "HV73XZR",
        model: "HYUNDAI KONA HATCH CAR",
        netCapital: "£29,450.00",
      },
      {
        registration: "BD73DYO",
        model: "NISSAN TOWNSTAR",
        netCapital: "£34,860.00",
      },
    ],
  },
  {
    identifier: "HSBC 31",
    type: "Motor Vehicle",
    contractNumber: "333520",
    registrationDoc: "YG74ZJZ",
    makeModel: "RENAULT TRAFIC CREW  DCI ADVANCE",
    startDate: "12 November 2024",
    termMonths: "48",
    endDate: "11 November 2028",
    netCapital: "£33,390.00",
    capitalCost: "£40,458.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YG74ZJZ",
        model: "RENAULT TRAFIC CREW  DCI ADVANCE",
        netCapital: "£33,390.00",
      },
    ],
  },
  {
    identifier: "HSBC 32",
    type: "Motor Vehicle",
    contractNumber: "333953",
    registrationDoc: "YC74XMH",
    makeModel: "RENAULT TRAFIC SL 30 BLUE DCI 130 ADVANCE",
    startDate: "28 November 2024",
    termMonths: "48",
    endDate: "27 November 2028",
    netCapital: "£29,310.00",
    capitalCost: "£35,562.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YC74XMH",
        model: "RENAULT TRAFIC SL 30 BLUE DCI 130 ADVANCE",
        netCapital: "£29,310.00",
      },
    ],
  },
  {
    identifier: "HSBC 33",
    type: "Motor Vehicle",
    contractNumber: "334237",
    registrationDoc: "YB24UVG",
    makeModel: "CITROEN RELAY 62 H2",
    startDate: "05 December 2024",
    termMonths: "48",
    endDate: "04/12/2028",
    netCapital: "£40,645.00",
    capitalCost: "£49,164.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YB24UVG",
        model: "CITROEN RELAY 62 H2",
        netCapital: "£40,645.00",
      },
    ],
  },
  {
    identifier: "HSBC 34",
    type: "Motor Vehicle",
    contractNumber: "335424",
    registrationDoc: "MA74WXK",
    makeModel: "RENAULT TRAFFIC LL30 EXTRA 150 EDC",
    startDate: "07 March 2025",
    termMonths: "48",
    endDate: "06 March 2029",
    netCapital: "£37,500.00",
    capitalCost: "£45,390.00",
    arrangementFee: "£0.00",
    financeInterest: "£5,083.20",
    initialPayment: "11,250.00",
    monthlyInstallment: "817.15",
    finalPayment: "",
    totalRepayment: "50,473.20",
    vehicles: [
      {
        registration: "MA74WXK",
        model: "RENAULT TRAFFIC LL30 EXTRA 150 EDC",
        netCapital: "£37,500.00",
      },
    ],
  },
  {
    identifier: "HSBC 35",
    type: "Equipment",
    contractNumber: "333959",
    registrationDoc: "",
    makeModel: "Variotec 460 - Tracer gas kit x14; Aquaphone A200x6, etc",
    startDate: "17 February 2025",
    termMonths: "48",
    endDate: "16 March 2029",
    netCapital: "£135,346.00",
    capitalCost: "£162,415.20",
    arrangementFee: "£200.00",
    financeInterest: "£20,686.20",
    initialPayment: "40,603.80",
    monthlyInstallment: "2,968.70",
    finalPayment: "",
    totalRepayment: "183,101.40",
    vehicles: [
      {
        registration: "",
        model: "Variotec 460 - Tracer gas kit x14; Aquaphone A200x6, etc",
        netCapital: "£135,346.00",
      },
    ],
  },
  {
    identifier: "HSBC 36",
    type: "Motor Vehicle",
    contractNumber: "338638",
    registrationDoc: "BF25XBW",
    makeModel: "NISSAN TOWN ICE L1 ACE BEN MY24.5",
    startDate: "01 May 2025",
    termMonths: "48",
    endDate: "30 April 2029",
    netCapital: "£21,510.00",
    capitalCost: "£26,212.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "BF25XBW",
        model: "NISSAN TOWN ICE L1 ACE BEN MY24.5",
        netCapital: "£21,510.00",
      },
    ],
  },
  {
    identifier: "HSBC 37",
    type: "Motor Vehicle",
    contractNumber: "338789",
    registrationDoc: "YB74XHM",
    makeModel: "TRAFIC LI30 BLUE DCI 130 ADVANCE",
    startDate: "07 May 2025",
    termMonths: "48",
    endDate: "06 May 2029",
    netCapital: "£33,595.00",
    capitalCost: "£40,704.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "YB74XHM",
        model: "TRAFIC LI30 BLUE DCI 130 ADVANCE",
        netCapital: "£33,595.00",
      },
    ],
  },
  {
    identifier: "HSBC 38",
    type: "Motor Vehicle",
    contractNumber: "340004",
    registrationDoc: "KR25GLJ",
    makeModel: "RENAULY TRAFFIC LL30 BLUE DCI 130 ADVANCE",
    startDate: "12 June 2025",
    termMonths: "48",
    endDate: "11 June 2029",
    netCapital: "£31,665.00",
    capitalCost: "£38,398.00",
    arrangementFee: "",
    financeInterest: "",
    initialPayment: "",
    monthlyInstallment: "",
    finalPayment: "",
    totalRepayment: "",
    vehicles: [
      {
        registration: "KR25GLJ",
        model: "RENAULY TRAFFIC LL30 BLUE DCI 130 ADVANCE",
        netCapital: "£31,665.00",
      },
    ],
  },
];
